# Generated by Django 5.1.6 on 2025-03-01 13:16

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ksss_code', models.IntegerField(unique=True, verbose_name='Код КССС Топлива')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование топлива')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид топлива',
                'verbose_name_plural': 'Виды топлива',
            },
        ),
        migrations.CreateModel(
            name='OilBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ksss_code', models.IntegerField(unique=True, verbose_name='Код КССС НБ')),
                ('name', models.CharField(max_length=255, verbose_name='Название нефтебазы')),
                ('region', models.CharField(max_length=255, verbose_name='Регион нефтебазы')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес нефтебазы')),
            ],
            options={
                'verbose_name': 'Нефтебаза',
                'verbose_name_plural': 'Нефтебазы',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата лота')),
                ('initial_volume', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Стартовый вес (л)')),
                ('available_volume', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Доступный остаток (л)')),
                ('status', models.CharField(choices=[('confirmed', 'Подтвержден'), ('sold', 'Продан'), ('inactive', 'Неактивен')], default='confirmed', max_length=10, verbose_name='Статус')),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена за 1 тонну (руб)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Общая стоимость лота (руб)')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='trade.fueltype', verbose_name='Вид топлива')),
                ('oil_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='trade.oilbase', verbose_name='Нефтебаза')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('oil_base_code', models.IntegerField(verbose_name='Код КССС НБ')),
                ('fuel_type_code', models.IntegerField(verbose_name='Код КССС Топлива')),
                ('volume', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Объём заказа (л)')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], default='pickup', max_length=10, verbose_name='Тип доставки')),
                ('price', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость сделки за у.е. (руб)')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trade.lot', verbose_name='Лот')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date'],
            },
        ),
    ]
