# Generated by Django 5.1.6 on 2025-03-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['-expiration_date', 'id'], 'verbose_name': 'Лот', 'verbose_name_plural': 'Лоты'},
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='date',
            new_name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='total_price',
        ),
    ]
