# Generated by Django 5.1.6 on 2025-03-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_lot_options_rename_date_lot_expiration_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_user', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fuel_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_fuel_type', to='trade.fueltype', verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oil_base_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_oil_base', to='trade.oilbase', verbose_name='Нефтяная база'),
        ),
    ]
