# Generated by Django 5.1.6 on 2025-03-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_order_options_remove_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fuel_type_code',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='oil_base_code',
            new_name='oil_base',
        ),
    ]
