# Generated by Django 5.1.6 on 2025-03-01 21:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_rename_fuel_type_code_order_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='available_volume',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Доступный остаток (т)'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='initial_volume',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Стартовый вес (т)'),
        ),
    ]
