# Generated by Django 5.1.6 on 2025-03-01 23:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_lot_available_volume_alter_lot_initial_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='initial_volume',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='Стартовый вес (т)'),
        ),
    ]
