# Generated by Django 5.1.6 on 2025-03-02 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_lot_initial_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltype',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lot',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lot',
            name='expiration_date',
            field=models.DateField(verbose_name='Дата лота'),
        ),
        migrations.AlterField(
            model_name='oilbase',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
