version: "3.8"

services:
  postgres:
    container_name: service-postgres
    image: postgres:17
    environment: &db_env
      POSTGRES_DB: besthack25_db
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - postgres_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword123
    ports:
      - "5050:80"
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.10.0/24
