version: '3.8'

services:
  ftp:
    build: .
    ports:
      - "${FTP_PORT:-2121}:2121"
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    restart: always
    networks:
      - ftp_network

networks:
  ftp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.2.0/24
